### ISSUE TITLE
what does sketch do?

### ISSUE THREAD

**Issue by queenidog** [RobTillaart/HC4067#9] opened 2024-11-10 18:50 UTC
What does the sketch hc4067_performance do?   What's the objective?  You don't state it and there are no comments in the sketch at all.  I ran it and get numbers from 16 to 32.  What are they?  In the sketch it says to set channel (10) but in the monitor display shows SetChannel 4.   So what is going on?  Please explain.  Sketch MAY be useful if I know what it does.

**Comment by RobTillaart** [comment] 2024-11-10 19:38
Thanks for your question.

> What does the sketch hc4067_performance do? 

It gives an indication of the time used by a call to **setChannel()** function.

It measures the time when setchannel changes the channel and when it is called without changing the channel.

The code is straightforward. Numbers are either channels or microseconds.

**Comment by queenidog** [comment] 2024-11-11 13:08
The reason I’m interested is that I’m having some issues with a 4067 reading 16 signals from linear Hall sensors.  The readings from the A/D (shown on monitor screen) from the NANO are all over the place, even with no magnets present.   Yet the voltage from each sensor, measured going into the mux,  is steady as a rock).  So the mux appears to not be properly capturing the data, or it’s the A/D in the Nano.  More testing is required (I’ll eliminate the mux and take single readings), but the mux is highly suspect.  Noise is not an issue, nor are stray magnetic fields.

 

So it’s a case of good data in, garbage data out.

**Comment by RobTillaart** [comment] 2024-11-11 15:32
What voltages do you see / use? 
Have you checked the datasheet if these are within operational range?

**Comment by queenidog** [comment] 2024-11-11 19:48
I had 6.5 volts on the Hall sensors but this was too much for the mux which is rated at 6 volts.  (The sensors have a bigger range than the mux). Knocking it down to 6 volts on the sensors made a quite significant change.  Other changes I made (using concentrators on the magnets) were not needed anymore to get good values.

 

I have 5x16 unit sensor boards and two types of magnet orientation (north and south poles) to test before I am “home free”.

 

Thanks for your reply.

**Comment by RobTillaart** [comment] 2024-11-11 20:26
@queenidog 
So the problem is solved?

**Comment by queenidog** [comment] 2024-11-11 23:23
It might be.  Good results on board #1, 4 more to test.  Also waiting for some different magnets and gauss meter to test them, to try and get the values as close as possible.

I’ll let you know, if you wish.

 

Bob 

Indian Harbour, NS

Canada

**Comment by RobTillaart** [comment] 2024-11-12 02:47
Yes, please let me know, as it might also help other people finding this topic.

**Comment by queenidog** [comment] 2024-11-12 23:35
Okay, all testing done of my 5x16 position Hall sensor boards.

I had been fighting with this for some time, getting spurious readings that made no sense.  I’m using AH49E analog Hall sensors with a CD4067 multiplexer, and Arduino Nano.  The boards are custom made by myself.

Specs for the Hall sensors was max 8V, with recommended 6.5 volts.   Knowing that more voltage would make the sensors more sensitive, I chose 6.5 volts, feeding them from a separate power supply.  The mux is rated at 7 volts absolute max with 6 volts typical.  I SHOULD have been okay, but as soon as I dropped the voltage on the Hall sensors to 6 Volts, all my values came into line.  Even when I only had 6.1 volt on the sensors, it was too much.

 

I have North pole magnets that drive the voltage down, and South pole magnets drive the voltage higher.  I was looking for a big differential so I could determine what magnet (N or S) was over a sensor.  Before the “fix”, the numbers would be all over the place (see left screenprint below) , but now they are steady (right screenprint).

 

So…bottom line, reducing sensor voltage to 6.0 volts from 6.5, (which was still on “spec”) and keeping all the rest the same, I went from spurious incomprehensible data to clear data.  I chased this for quite awhile because I had no idea what the Gauss value was of my magnets. .  I used different muxes, different Nanos, worked on decoupling, reducing noise, changing delays in the program.   Any slight variation in the good data output is due likely to mismatched magnets and/or off-axis positioning, but I can handle that.

 

Oh…the program I had been using was storing the values in an array, then printing the array out.  The new data is from “real-time”, no data storage, values. For the array program I was reading the values anywhere from once in each loop to 10 times in each loop.  Didn’t help.

 

 

      

These values for North pole magnets are INCORRECT                                                                                       These values for  the same pieces are CORRECT

 

 



Top board with white chess pieces, magnets are south pole  Board at botoom shows the

Hall sensors.

 

Cheers,

Bob Found

**Comment by RobTillaart** [comment] 2024-11-13 07:34
Thanks for this informative feedback, appreciated

**Comment by RobTillaart** [comment] 2024-11-14 09:29
The screen prints are missing in your post, 
is it possible to post them again?

**Comment by queenidog** [comment] 2024-11-14 12:35
Here they are.  First print is bad data from 6.5 volt P/S on sensors, second (lower more consistent voltages) are with 6.0 volt on sensors.  Bottom photo is setup.  If these photos don’t appear, I can make them as file attachments instead of putting in text.

**Comment by RobTillaart** [comment] 2024-11-14 13:48
>  If these photos don’t appear, I can make them as file attachments instead of putting in text.

no images
look with your browser to - https://github.com/RobTillaart/HC4067/issues/9

Please attach them.

**Comment by queenidog** [comment] 2024-11-15 00:26
Okay I’ll try again.  They are being sent as attachments this time.  ( I sent these to a friend across Canada..and he received them).

They are really small, so that shouldn’t be the problem.   (I copied them from the email I sent)

**Comment by RobTillaart** [comment] 2024-11-15 10:42
Sorry but it fails, the attachments do not appear so through a browser seems the only way.
Thanks for your efforts.

**Comment by queenidog** [comment] 2024-11-15 12:20
Let me post them to my website or to Google Drive

**Comment by queenidog** [comment] 2024-11-15 12:43
Try this:  https://www.dropbox.com/scl/fi/yjk6i9rplcww444yk32eo/corrent.png?rlkey=0a79fayig108nh8shq489o2rm <https://www.dropbox.com/scl/fi/yjk6i9rplcww444yk32eo/corrent.png?rlkey=0a79fayig108nh8shq489o2rm&st=8zxw7yvw&dl=0> &st=8zxw7yvw&dl=0

 

I put the three photos on Dropbox.

**Comment by RobTillaart** [comment] 2024-11-15 12:52
First image (copied)
![HC4067_01](https://github.com/user-attachments/assets/d25ea578-dea5-4f12-8c3b-45de55120013)

it is the only one I see

**Comment by RobTillaart** [comment] 2024-11-18 08:33
As this issue is essentially solved I close the issue (keeps my backlog a bit smaller ;)
Feel free to reopen if questions remain

**Closed as completed by RobTillaart** 2024-11-18 08:33 UTC
Labels: question
